### PR TITLE
Publish package with progress controller callback

### PR DESCRIPTION
**Pull request by begoldsm**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Description of the change
Updating the package version to publish the progress controller
callback.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change and a version increment.
- [x] The PR has supporting test coverage that confirm the expected behavior and protects against regressions, including necessary recordings.
- [ ] Links to associated bugs, if any, are in the description.

### CODE REVIEW

**Comment by begoldsm** [comment]
This publishes the fix for issue: https://github.com/Azure/azure-data-lake-store-python/issues/174

**Comment by clehene** [comment]
Glad to see this :)

A note on the release / master version:
Once 0.0.15 is published, wouldn't it be better if the master version would become 0.0.16-dev (or snapshot)?

**Comment by asikaria-msft** [comment]
@clehene, do you mean to change the version in __init__.py to make it 0.0.16-dev, or do you mean to create a git branch for the next version?

**Comment by clehene** [comment]
@asikaria-msft - I mean changing init.py (master) to make it `0.0.16-dev`, which would be a logical signal that all changes in master are going to get released in 0.0.16 and any intermediate build would be a dev version of `0.0.16`(`-dev`).

**Pull request merged**
